apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-configmap
data:
{{ if .Values.customConfig.enabled }}
  config.toml: |-
{{ .Values.customConfig.toml | indent 4 }}
{{ end }}
